apiVersion: 1

datasources:
  - name: Dialed Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: dialed-prometheus
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 30s
  - name: Dialed Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: dialed-loki
    isDefault: false
    editable: false
